---
title: "MENDsimulations"
author: "Jianqiu Zheng"
date: "7/15/2021"
output: html_document
---



```{r setup, include=FALSE}
library(ggplot2)
library(ggpubr)
library(scales)
library(MASS) # to access Animals data sets
library(ggallin)
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(ggpmisc)
theme_pubr()
```

##Figure 1 Comparing effect of 3 exchange component

```{r data}
ex<-read.delim("vanD_peat_fresh_ex.txt",header=TRUE)
om<-read.delim("vanD_peat_fresh_om.txt",header=TRUE)
hfo<-read.delim("vanD_peat_fresh_hfo.txt",header=TRUE)
ex<-ex[-1, ]
om<-om[-1, ]
hfo<-hfo[-1, ]

df<-data.frame(matrix(NA, nrow=15))
df$time<-obv$time
df$ex<-ex$NH4*1000
df$om<-om$NH4*1000
df$hfo<-hfo$NH4*1000
df<-df[,-1]

newdf<-reshape2::melt(df, id.var="time")

plot1<-ggplot(newdf, mapping=aes(time, value, color=variable))+geom_line(linewidth=1)+ 
  scale_color_manual(values = c("#8073ac","#b35806","#309d8e","#7f3b08"))+
  scale_y_continuous(limits=c(0,0.5), breaks=c(0,0.25,0.5))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(strip.text=element_text(size=18, face="bold"))+xlab("Time(Day)")+ylab("NH4 (mM)")

pdf("NH4_3settings.pdf",width=4, height=2.5)
plot1
dev.off()


```



##load data
```{r data}

fresh<-read.csv("peat_fresh.csv",header=TRUE)
fresh$time<-c(6,19,33,47,62,75,89,103,117,131,145,159,173,187,201)

salt<-read.csv("peat_salt.csv",header=TRUE)
salt$time<-c(6,19,33,47,62,75,89,103,117,131,145,159,173,187,201)

mod1<-read.delim("peat_fresh_low.txt",header=TRUE)
mod1<-mod1[-(1:2), ]
mod1$time<-seq(1:200)

mod2<-read.delim("peat_fresh_ref.txt",header=TRUE)
mod2<-mod2[-(1:2), ]
mod2$time<-seq(1:200)

mod3<-read.delim("peat_fresh_high.txt",header=TRUE)
mod3<-mod3[-(1:2), ]
mod3$time<-seq(1:200)


salt1<-read.delim("peat_salt_low.txt",header=TRUE)
salt1<-salt1[-(1:2), ]
salt1$time<-seq(1:200)

salt2<-read.delim("peat_salt_ref.txt",header=TRUE)
salt2<-salt2[-(1:2), ]
salt2$time<-seq(1:200)

salt3<-read.delim("peat_salt_high.txt",header=TRUE)
salt3<-salt3[-(1:2), ]
salt3$time<-seq(1:200)

ctf<-read.delim("vanD_peat_fresh_ctrl.txt",header=TRUE)
ctf<-ctf[-1, ]
cts<-read.delim("vanD_peat_salt_ctrl.txt",header=TRUE)
cts<-cts[-1, ]

####-----------------------
df<-data.frame(matrix(NA, nrow=200))
df$time<-mod1$time
df$lwr<-mod1$SO4*1000
df$ref<-mod2$SO4*1000
df$upr<-mod3$SO4*1000
df<-df[,-1]


ds<-data.frame(matrix(NA, nrow=200))
ds$time<-salt1$time
ds$lwr<-salt1$SO4*1000
ds$ref<-salt2$SO4*1000
ds$upr<-salt3$SO4*1000
ds<-ds[,-1]

obv<-data.frame(matrix(NA, nrow=15))
obv$time<-fresh$time
obv$Freshwater<-fresh$SO4
obv$Saltwater<-salt$SO4
obv<-obv[,-1]

obvdf<-reshape2::melt(obv, id.var="time")


ctrl<-data.frame(matrix(NA, nrow=15))
ctrl$time<-fresh$time
ctrl$fresh<-ctf$NH4*1000
ctrl$salt<-cts$NH4*1000
ctrl<-ctrl[,-1]

ctdf<-reshape2::melt(ctrl, id.var="time")


plot1<-ggplot()+geom_point(obvdf, mapping=aes(time, value, color=variable), size=2)+
 scale_y_continuous(limits=c(0,6), breaks=c(0,3,6))+
  scale_x_continuous(limits=c(0,205), breaks=c(0,100,200))+
 scale_color_manual(values = c("#b35806","#8073ac"))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(strip.text=element_text(size=18, face="bold"))+xlab("Time(Day)")+ylab("SO4 (mM)")

plot2<-plot1+
  geom_line(data=df, mapping=aes(x=time, y=ref),color="#b35806",linewidth=1.2 )+geom_ribbon(data=df, aes(x=time, ymin=lwr, ymax=upr), alpha=0.3,inherit.aes=F, fill="#b35806" )

plot3<-plot2+
  geom_line(data=ds, mapping=aes(x=time, y=ref),color="#8073ac",linewidth=1.2 )+geom_ribbon(data=ds, aes(x=time, ymin=lwr, ymax=upr), alpha=0.3,inherit.aes=F, fill="#8073ac" )

plot4<-plot3+geom_line(data=ctdf, mapping=aes(x=time, y=value, color=variable),linetype="dashed",linewidth=1 )
plot4



pdf("new_peat_SO4_noctrl.pdf",width=4.2, height=2.5)
plot3
dev.off()



#------------------

df<-data.frame(matrix(NA, nrow=200))
df$time<-mod1$time
df$lwr<-mod1$pH
df$ref<-mod2$pH
df$upr<-mod3$pH




ds<-data.frame(matrix(NA, nrow=200))
ds$time<-salt1$time
ds$lwr<-salt1$pH
ds$ref<-salt2$pH
ds$upr<-salt3$pH



obv<-data.frame(matrix(NA, nrow=15))
obv$time<-fresh$time
obv$fresh<-fresh$pH
obv$salt<-salt$pH
obv<-obv[,-1]

obvdf<-reshape2::melt(obv, id.var="time")


ctrl<-data.frame(matrix(NA, nrow=15))
ctrl$time<-fresh$time
ctrl$fresh<-ctf$pH
ctrl$salt<-cts$pH
ctrl<-ctrl[,-1]

ctdf<-reshape2::melt(ctrl, id.var="time")


plot1<-ggplot()+geom_point(obvdf, mapping=aes(time, value, color=variable), size=2)+
scale_y_continuous(limits=c(6,10), breaks=c(6,8,10))+
  scale_x_continuous(limits=c(0,205), breaks=c(0,100,200))+
 scale_color_manual(values = c("#b35806","#8073ac"))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(strip.text=element_text(size=18, face="bold"))+xlab("Time(Day)")+ylab("pH")

plot2<-plot1+
  geom_line(data=df, mapping=aes(x=time, y=ref),color="#b35806",linewidth=1.2 )+geom_ribbon(data=df, aes(x=time, ymin=lwr, ymax=upr), alpha=0.3,inherit.aes=F, fill="#b35806" )

plot3<-plot2+
  geom_line(data=ds, mapping=aes(x=time, y=ref),color="#8073ac",linewidth=1.2 )+geom_ribbon(data=ds, aes(x=time, ymin=lwr, ymax=upr), alpha=0.3,inherit.aes=F, fill="#8073ac" )

plot4<-plot3+geom_line(data=ctdf, mapping=aes(x=time, y=value, color=variable),linetype="dashed",linewidth=1 )
plot4



pdf("clay_pH.pdf",width=3.8, height=2.5)
plot4
dev.off()



```

## Salinity buffering--effect size figure
```{r data}

ctf<-read.delim("clay_salt_ref.txt",header=TRUE)
ctf<-ctf[-1, ]
ctf<-ctf[,-12]

cts<-read.delim("vanD_clay_salt_ctrl.txt",header=TRUE)##no exchanger
cts<-cts[-1, ]
cts<-cts[,-12]
df_3ex<-log(ctf)-log(cts)
df_3ex<-df_3ex[-1, ]
df_new<-df_3ex[, c("Na","Ca","SO4","NH4", "PO4","sc","pH")]
colnames(df_new)<-c("Na","Ca","SO4","NH4", "PO4","SC","pH")
df_new$pH<-df_new$pH*1.2

df<-reshape2::melt(df_new)

plot1<-ggplot(df, mapping=aes(variable, value), size=2)+geom_boxplot(color="#2d004b")+geom_hline(yintercept=0, linetype="dashed")+ scale_y_continuous(limits=c(-2,2), breaks=c(-2,0,2))+
  theme_pubr(border=TRUE)+theme(legend.position="right")+theme(strip.text=element_text(size=18, face="bold"))+coord_flip()

pdf("buffering_effect_size.pdf", width=3, height=5)
plot1
dev.off() 

```


 #-----------------------figure testing individual exchanger---------------------
```{r exchanger}
 
ctf<-read.delim("peat_salt_ref.txt",header=TRUE)
ctf<-ctf[-1, ]
ctf<-ctf[,-12]

cts<-read.delim("vanD_peat_salt_ctrl.txt",header=TRUE)
cts<-cts[-1, ]
cts<-cts[,-12]
df_3ex<-log(cts)-log(ctf) 

cts1<-read.delim("peat_salt_ref_noOM.txt",header=TRUE)
cts1<-cts1[-1, ]
cts1<-cts1[,-12]
df_om<-log(cts1)-log(ctf) 

cts2<-read.delim("peat_salt_ref_noCEC.txt",header=TRUE)
cts2<-cts2[-1, ]
cts2<-cts2[,-12]
df_CEC<-log(cts2)-log(ctf) 

cts3<-read.delim("peat_salt_ref_noHfo.txt",header=TRUE)
cts3<-cts3[-1, ]
cts3<-cts3[,-12]
df_Hfo<-log(cts3)-log(ctf) 

df_3ex<-df_3ex[-1,]
df_om<-df_om[-1,]
df_CEC<-df_CEC[-1,]
df_Hfo<-df_Hfo[-1,]

df_3ex$exchanger<-c("no_Buffer")
df_om$exchanger<-c("no_OM")
df_CEC$exchanger<-c("no_CEC")
df_Hfo$exchanger<-c("no_Hfo")

clay_abstest<-rbind(df_3ex, df_CEC, df_Hfo, df_om)
write.csv(clay_abstest,"peat_abstest.csv")

#-----subsetting data for ploting------------------
df_om_cation<-df_om[, c("Na","K","Ca","Mg","NH4", "PO4","Cl","SO4","sc","pH")]
df_om_cation<-df_om_cation[-1,]
df_om_cation$exchanger<-c("OM")


df_Hfo_cation<-df_Hfo[, c("Na","K","Ca","Mg","NH4", "PO4","Cl","SO4","sc","pH")]
df_Hfo_cation<-df_Hfo_cation[-1,]
df_Hfo_cation$exchanger<-c("Hfo")

df_cec_cation<-df_X[, c("Na","K","Ca","Mg","NH4", "PO4","Cl","SO4","sc","pH")]
df_cec_cation<-df_cec_cation[-1,]
df_cec_cation$exchanger<-c("CEC")


df_cation_temp<-rbind(df_om_cation, df_Hfo_cation, df_cec_cation)

write.csv(df_cation_temp,"EffSize_clay_salt.csv")

#####--------------------------------------------------


df_cation_temp<-rbind(df_om_cation, df_Hfo_cation, df_cec_cation)

df<-reshape2::melt(df_om_cation, id.var="exchanger")


plot1<-ggplot(df, mapping=aes(variable, value, fill="#e08214"), size=2)+geom_boxplot(outlier.shape=NA, lwd=0.3, width=0.7)+geom_hline(yintercept=0, linetype="dashed")+ scale_y_continuous(limits=c(-2, 3), breaks=c(-2,0,2))+scale_fill_manual(values = c("#e08214"))+
  theme_pubr(border=TRUE)+theme(legend.position="right")+theme(strip.text=element_text(size=16, face="bold"))+ggtitle("Clay_Hfo")

pdf("clay_Hfo.pdf", width=5, height=2)
plot1
dev.off() 

#-------------------- Salt vs. freshwater treatment effect ------------
ctf<-read.delim("vanD_peat_fresh_ctrl_Hfo.txt",header=TRUE)
ctf<-ctf[-1, ]
ctf<-ctf[,-12]
cts<-read.delim("vanD_peat_salt_ctrl_Hfo.txt",header=TRUE)
cts<-cts[-1, ]
cts<-cts[,-12]
df_Hfo<-log(cts)-log(ctf) 
df_Hfo$soil<-c("peat")
df_Hfo$exchanger<-c("Hfo")

ctf<-read.delim("vanD_peat_fresh_ctrl_om.txt",header=TRUE)
ctf<-ctf[-1, ]
ctf<-ctf[,-12]
cts<-read.delim("vanD_peat_salt_ctrl_om.txt",header=TRUE)
cts<-cts[-1, ]
cts<-cts[,-12]
df_om<-log(cts)-log(ctf) 
df_om$soil<-c("peat")
df_om$exchanger<-c("om")

ctf<-read.delim("vanD_peat_fresh_ctrl_ex.txt",header=TRUE)
ctf<-ctf[-1, ]
ctf<-ctf[,-12]
cts<-read.delim("vanD_peat_salt_ctrl_ex.txt",header=TRUE)
cts<-cts[-1, ]
cts<-cts[,-12]
df_cec<-log(cts)-log(ctf) 
df_cec$soil<-c("peat")
df_cec$exchanger<-c("cec")

df_temp<-rbind(df_Hfo, df_om, df_cec)
test<-subset(df_temp, select=-c(pH, sc, HCO3))
write.csv(test, "salinity_effect_size_peat.csv")

#---------
clay<-read.csv("salinity_effect_size_clay.csv")
peat<-read.csv("salinity_effect_size_peat.csv")
obv<-read.csv("all_soil_effect_size.csv")
obv<-subset(obv, select=-c(X))
obv$exchanger<-c("a")

#-----
ctf<-read.delim("vanD_peat_salt_ctrl.txt",header=TRUE)
ctf<-ctf[-1, ]
ctf<-ctf[,-12]
cts<-read.delim("vanD_peat_salt_ref.txt",header=TRUE)
cts<-cts[-1, ]
cts<-cts[,-12]
df_peat<-log(cts)-log(ctf) 


ctf<-read.delim("vanD_clay_salt_ctrl.txt",header=TRUE)
ctf<-ctf[-1, ]
ctf<-ctf[,-12]
cts<-read.delim("vanD_clay_salt_ref.txt",header=TRUE)
cts<-cts[-1, ]
cts<-cts[,-12]
df_clay<-log(cts)-log(ctf) 
df_3ex<-rbind(df_clay, df_peat)
df_3ex<-df_3ex[, c("Na","K","Ca","Mg","NH4", "PO4","Cl","SO4","sc","pH")]
df_3ex<-df_3ex[-1,]
df_3ex$exchanger<-c("3ex")

df_temp<-rbind(clay, peat)
df_temp<-subset(df_temp, select=-c(X))

df_new<-rbind(df_3ex, df_temp)
df<-reshape2::melt(df_new, id.var=c("exchanger"))


data1<-subset(df, variable=="pH")
plot1<-ggplot(data1, mapping=aes(variable, value, color=exchanger, fill=exchanger, alpha=exchanger))+
  geom_boxplot(outlier.shape=NA, lwd=0.6, position=position_dodge(width=0.9))+scale_y_continuous(limits=c(-0.2,0.2))+
  geom_hline(yintercept=0, linetype="dashed")+scale_color_manual(values = c("#8073ac","#fee0b6","#e08214","#7f3b08"))+scale_fill_manual(values = c("#8073ac","white","white","white"))+scale_alpha_manual(values=c(0.5,0.5,0.5,0.5))+
  theme_pubr(border=TRUE)+theme(legend.position="NA")+theme(strip.text=element_text(size=16, face="bold"))+ylab("Response ratio")+xlab(" ")
plot1


pdf("salt_ctrl_pH.pdf", width=2.05, height=2.2)
plot1
dev.off() 




```


### another way to show sensitivity

```{r exchanger}
 
ctf<-read.delim("clay_sen_salt_ctrl_Href.txt",header=TRUE)
ctf<-ctf[-1, ]
ctf<-ctf[,-12]

cts1<-read.delim("clay_sen_salt_ctrl_H05.txt",header=TRUE)
cts1<-cts1[-1, ]
cts1<-cts1[,-12]
df_om05<-log(cts1)-log(ctf) 
df_om05<-df_om05[-1, ]
df_om05$trt<-c("red")
  
cts2<-read.delim("clay_sen_salt_ctrl_H15.txt",header=TRUE)
cts2<-cts2[-1, ]
cts2<-cts2[,-12]
df_om15<-log(cts2)-log(ctf) 
df_om15<-df_om15[-1, ]
df_om15$trt<-c("inc")

df_om<-rbind(df_om05, df_om15)
write.csv(df_om, "sen_salt_H.csv")
```

##graphing
```{r graphing}
clay<-read.csv("clay_abstest.csv")
peat<-read.csv("peat_abstest.csv")
df_temp<-rbind(clay, peat)
new<-str_replace(df_temp$exchanger, "no_Buffer", "Ctrl")
df_temp$exchanger<-new

df_temp<-subset(df_temp, select=-c(X, HCO3,pH))
df_temp<-df_temp[, c("Ca","Mg","Na","K","SO4","PO4","NH4","Cl","sc","exchanger")]
colnames(df_temp)<-c("Ca","Mg","Na","K","SO4","PO4","NH4","Cl","SC","exchanger")
data1<-reshape2::melt(df_temp, id.var=c("exchanger"))


plot1<-ggplot(data1, mapping=aes(exchanger, value, color=exchanger, fill=exchanger, alpha=exchanger))+
  geom_boxplot(outlier.shape=NA, lwd=0.6, position=position_dodge(width=0.9))+scale_y_continuous(limits=c(-3.2,3.2))+
  geom_hline(yintercept=0, linetype="dashed")+scale_color_manual(values = c("#8073ac","#fee0b6","#e08214","#7f3b08"))+scale_fill_manual(values = c("#8073ac","white","white","white"))+scale_alpha_manual(values=c(0.5,0.5,0.5,0.5))+
  theme_pubr(border=TRUE)+theme(legend.position="NA")+theme(strip.text=element_text(size=14, face="bold"))+ylab("Response ratio")+xlab(" ")+ theme(axis.text.x = element_text(angle = 60, vjust = 0.2, hjust=0.3))+theme(strip.background = element_rect(fill="white"))+
  facet_wrap(~variable, ncol=5)
plot1




plot1<-ggplot(data1, mapping=aes(exchanger, value, color=exchanger, fill=exchanger, alpha=exchanger))+
  geom_boxplot(outlier.shape=NA, lwd=0.6, position=position_dodge(width=0.9))+scale_y_continuous(limits=c(-3.1,3.1))+
  geom_hline(yintercept=0, linetype="dashed")+scale_color_manual(values = c("#8073ac","#fee0b6","#e08214","#7f3b08"))+scale_fill_manual(values = c("#8073ac","white","white","white"))+scale_alpha_manual(values=c(0.5,0.5,0.5,0.5))+
  theme_pubr(border=TRUE)+theme(legend.position="NA")+theme(strip.text=element_text(size=14, face="bold"))+ylab("Response ratio")+xlab(" ")+ theme(axis.text.x = element_blank())+theme(strip.background = element_rect(fill="white"))+
  facet_wrap(~variable, ncol=5)
plot1



pdf("clay_abs_response_axis.pdf", width=8, height=5)
plot1
dev.off() 

```




##graph all soils
```{r plot}

Ul<-read.csv("Ultisol_control.csv",header=TRUE)
Ge<-read.csv("Gelisol_control.csv",header=TRUE)
Mo<-read.csv("Mollisol_control.csv",header=TRUE)
An<-read.csv("Andisol_control.csv",header=TRUE)

SUl<-read.csv("Ultisol_simulations.csv",header=TRUE)
SGe<-read.csv("Gelisol_simulations.csv",header=TRUE)
SMo<-read.csv("Mollisol_simulations.csv",header=TRUE)
SAn<-read.csv("Andisol_simulations.csv",header=TRUE)



pdf("4soils.pdf", width=6, height=4)
par(xpd = T, mar = par()$mar + c(0,0,0,10))
plot(Ul$time,Ul$IC/23.484, xlab = "Time (d)", ylab = "Respiration (mgC g-1 C)", pch=16, cex=1.2,col="#b35806", xlim=c(0,400), ylim=c(0,0.2),cex.lab=1.2, cex.axis=1.2)
lines(SUl$time,SUl$IC/23.484, lwd=2, col="#b35806")
points(Mo$time,Mo$IC/32.198, pch=16, cex=1.2, col="#fdb863")
lines(SMo$time,SMo$IC/32.198, lwd=2, col="#fdb863")
points(An$time,An$IC/86.592, pch=16, cex=1.2, col="#b2abd2")
lines(SAn$time,SAn$IC/86.592, lwd=2, col="#b2abd2")
points(Ge$time,Ge$IC/15.52, pch=16, cex=1.2, col="#542788")
lines(SGe$time,SGe$IC/15.52, lwd=2, col="#542788")


legend("topright",inset = c(- 0.6, 0), c("Tropical","Temperate","Subarctic","Arctic"), lwd=2, lty=1,col=c("#b35806","#fdb863","#b2abd2","#542788"))


dev.off()


pdf("test.pdf", width=6, height=4)
plot(SUl$time,SUl$MOM/23.484, lwd=2, col="#b35806",xlim=c(0,400), ylim=c(0,1))
points(SMo$time,SMo$MOM/32.198, lwd=2, col="#fdb863")
points(SAn$time,SAn$MOM/86.592, lwd=2, col="#b2abd2")
points(SGe$time,SGe$MOM/15.52, lwd=2, col="#542788")
legend("topright",inset = c(- 0.6, 0), c("Tropical","Temperate","Sub-arctic","Arctic"), lwd=2, lty=1,col=c("#b35806","#fdb863","#b2abd2","#542788"))
dev.off

```

##
```{R plot}
pool<-read.csv("Poolsize2.csv")
p1<-ggplot(pool, aes(x=sample, y=value,fill=sample, color=sample))+geom_bar( stat="identity",size=0.08)+ #geom_smooth(aes(fill=series),alpha=0.2)+
  facet_wrap(~fraction)+
scale_fill_manual(values=c("#b35806","#fdb863","#b2abd2","#542788"))+
scale_color_manual(values=c('white','white','white','white'))+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=10))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 10, colour = "black"),axis.text.x=element_text(angle =45, vjust = 0.5))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1
pdf("poolsize2.pdf",width=4, height=2)
p1
dev.off()
```


```{R plot}
pool<-read.csv("nutnet.csv")
pw<-data.frame(pH=pool$Obv)
pw$no<-pool$No_OL
pw$om<-pool$OL
pw<-melt(pw, id.var=c("pH"))

# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pw, aes(x=pH, y=value, color=variable))+geom_point()+ 
  geom_smooth(method=lm, aes(fill=variable))+scale_color_manual(values=c("#8073ac","#b35806"))+
scale_fill_manual(values=c("#8073ac","#b35806"))+ scale_x_continuous(name = 'Observed pH',labels=scaleFUN) + scale_y_continuous(name = 'Predicted pH',labels=scaleFUN)+ geom_abline(intercept=0,slope=1, color="black", linetype="dashed")+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=14))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 14, colour = "black"))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("nutnetpH.pdf",width=4, height=2.5)
p1
dev.off()
```


```{R plot}
pka<-read.csv("pKas.csv")

# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pka, aes(x=pKa))+geom_histogram(binwidth=1,color="#b35806", fill="white")+ scale_y_continuous(name = 'Frequency')+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=16))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 16, colour = "black"))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("pKa.pdf",width=4, height=2.5)
p1
dev.off()
```

##pH sensitivity of exoenzymes
```{R plot}
pool<-read.csv("Cellobiohydrolase.csv")
# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pool, aes(x=pH, y=Activity))+geom_point(color="#b35806")+ 
  geom_smooth(method=loess, color="#b35806", fill="#b35806")+geom_vline(xintercept=7,color="black", linetype="dashed")+geom_vline(xintercept=6,color="black", linetype="dashed")+geom_vline(xintercept=5,color="black", linetype="dashed")+geom_vline(xintercept=4,color="black", linetype="dashed")+
scale_x_continuous(name = 'Observed pH',limits=c(2,12), breaks=c(2,4,6,8,10,12)) + scale_y_continuous(name = 'Relative activity',labels=scaleFUN)+ 
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=12))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 12, colour = "black"))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("CellopH.pdf",width=3, height=2)
p1
dev.off()
```



##soil pH 
```{R plot}
pool<-read.csv("soilph.csv")


# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pool, aes(x=pH, y=value, color=soil))+geom_point()+ 
  geom_smooth(method=loess,aes(fill=NA))+scale_color_manual(values=c("#b2abd2","#8073ac","#542788"))+
scale_fill_manual(values=c("#b2abd2","#8073ac","#542788"))+ scale_x_continuous(name = 'Observed pH',limits=c(2,12), breaks=c(2,4,6,8,10,12)) + scale_y_continuous(name = 'Relative activity',labels=scaleFUN)+ geom_vline(xintercept=7,color="black", linetype="dashed")+geom_vline(xintercept=6,color="black", linetype="dashed")+geom_vline(xintercept=5,color="black", linetype="dashed")+geom_vline(xintercept=4,color="black", linetype="dashed")+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=12))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 12, colour = "black"))+theme(legend.position="none")#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("soilpH.pdf",width=3, height=2)
p1
dev.off()
```

##soil pH 
```{R plot}
def1<-read.csv("def1.csv")
def2<-read.csv("def2.csv")
def3<-read.csv("def3.csv")
def4<-read.csv("def4.csv")
def5<-read.csv("def5.csv")

test<-rbind(def1, def2, def3, def4, def5)


# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(test, aes(x=mu, y=pH, color=level))+geom_point()+ 
  geom_smooth(method=loess,aes(fill=NA))+scale_color_manual(values=c("#fee0b6","#fdb863","#e08214","#b35806","#7f3b08"))+geom_hline(yintercept=5.42,color="black", linetype="dashed")+
scale_fill_manual(values=c("#fee0b6","#fdb863","#e08214","#b35806","#7f3b08"))+ scale_x_continuous(name = 'Ionic strength (mmol/L)') + scale_y_continuous(name = 'pH',labels=scaleFUN)+ 
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=14))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 14, colour = "black"))+theme(legend.position="none")#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("muPH.pdf",width=4, height=2.5)
p1
dev.off()
```


```{r fph}
#====pH response function====
pH<-seq(2,12,0.01)
fpHref<-10^(-0.2235*pH^2+2.7727*pH -8.6)
f3<-fpHref/max(fpHref)

f2<-(pH-4)*(pH-10)/((pH-4)*(pH-10)-(pH-7)^2)

ph1<-seq(2,7,0.01)
fph1<-1.02/(1.02+10^6*exp(-2.5*ph1))
ph2<-seq(7.01,12,0.01)
fph2<-1.02/(1.02+10^6*exp(-2.5*(14-ph2)))

data1<-data.frame(pH=ph1)
data1$fpH1<-fph1

data2<-data.frame(pH=ph2)
data2$fpH1<-fph2

allf<-rbind(data1, data2)
allf$fpH2<-f2
allf$fpH3<-f3

fpHs<-melt(allf, id.var=c("pH"))

plot1<-ggplot(fpHs, aes(x = pH,y = value, color=variable)) +
  scale_x_continuous(name = 'pH', breaks=c(0,2,4,6,8,10,12,14)) +
  scale_y_continuous(name = 'Relative activity', limits=c(0,1)) + geom_line(aes(color=variable),size=1)+
  scale_color_manual(values =c("#fee0b6","#e08214","#7f3b08"))
plot2<-plot1+theme_linedraw()+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=14))
plot2

pdf("fpH.pdf",width=5, height=2.8)
plot2
dev.off()
```