---
title: "MENDsimulations"
author: "Jianqiu Zheng"
date: "7/15/2021"
output: html_document
---



```{r setup, include=FALSE}
library(ggplot2)
library(ggpubr)
library(scales)
library(MASS) # to access Animals data sets
library(ggallin)
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(ggpmisc)
theme_pubr()
```

##Figure 1 Comparing effect of 3 exchange component

```{r data}
obv<-read.csv("annual_model.csv")

basedata<-obv%>% 
  group_by(treatment) %>%
  summarize(start=min(parameter, end=max(parameter))) %>%
  rowwise() %>%
  mutate(tigle=mean(c(start, end)))
basedata$tigle<-3
basedata$end<-c("a12","a24","a21","a33","a18","a30","a15","a27")
  
xgrid<-c(0,2,4,6)
obv$y1<-3.5
obv$y2<-3.89
plot1<- ggplot(obv, aes(parameter)) +
  geom_hline(yintercept=xgrid, colour="grey90", size=0.3) +
  geom_segment(data=data.frame(x=unique(obv$parameter), y=0, yend=5.6), aes(x=x, xend=x, y, yend=yend), colour='grey80', linewidth=0.3, position=position_nudge(x=0.5)) +
  geom_segment(data=data.frame(x=0.5), x=0.5, xend=0.5, y=0, yend=5.6, colour='grey80', size=0.3) +
  geom_ribbon(aes(x=1:length(parameter),ymin=3.59, ymax=3.89), fill="#b2abd2", alpha=0.5)+
  geom_col(aes(y=IC, color=process, fill=parameter), width=0.5, position="identity") +
  geom_errorbar(aes(ymin=IC - stdev, ymax=IC+ stdev, colour=process), 
                position=position_dodge(0.2), width=0.2) 
plot2<-plot1+
  annotate(y=xgrid, x=0, label=xgrid, geom="text", size=5) +
  coord_polar(start=-2*pi/25 * 0.5) + 
  scale_y_continuous(limits=c(0,6), expand=c(-0.1,2)) +
  expand_limits(y=2, x=-0.2) +
  #geom_text(data=basedata, aes(x=treatment, y=6, label=treatment), size=3, colour="grey30") +
  geom_segment(data=basedata, aes(x=start, y= 5.5, xend=end, yend=5.5), size=0.6, colour="grey30", inherit.aes = FALSE) +
  theme_bw() + 
  theme(panel.grid.major=element_blank(),
        axis.text=element_blank(),
        legend.title=element_blank(),
        panel.border=element_blank(),
        axis.ticks=element_blank(),
        axis.title=element_blank(), 
        legend.position=c("NA"),
        plot.background=element_rect(colour=NA)) +
  labs(fill="", colour="") + 
  scale_colour_manual(values=c("#b35806","#8073ac","#fdb863"))+
  #scale_fill_manual(values=c("white","white" ,"white"))
scale_fill_manual(values=c("#b35806","#8073ac","#fdb863","#b35806","#8073ac","#fdb863","#b35806","#8073ac","#fdb863","#b35806","#8073ac","#fdb863","white","white" ,"white","white","white","white" ,"white","white","white","white" ,"white","white"))

pdf("allprocess_lowSR_order.pdf",width=10, height=10)
plot2
dev.off()

```


