---
title: "MENDsimulations"
author: "Jianqiu Zheng"
date: "7/15/2021"
output: html_document
---



```{r setup, include=FALSE}
library(ggplot2)
library(ggpubr)
library(scales)
library(MASS) # to access Animals data sets
library(ggallin)
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(ggpmisc)
theme_pubr()
```

##Figure 1 Comparing salt buffering

```{r data}



mod1<-read.delim("fixp_redox_sw1.txt",header=TRUE)
mod1<-mod1[-1, ]

mod2<-read.delim("fixp_redox_sw2.txt",header=TRUE)
mod2<-mod2[-1, ]

mod3<-read.delim("fixp_redox_sw3.txt",header=TRUE)
mod3<-mod3[-1, ]

mod4<-read.delim("fixp_redox_sw4.txt",header=TRUE)
mod4<-mod4[-1, ]

mod5<-read.delim("fixp_redox_sw5.txt",header=TRUE)
mod5<-mod5[-1, ]



#-----sensitivity plot-------

df<-data.frame(matrix(NA, nrow=nrow(mod1)))
df$time<-mod1$Time
df$sw1<-mod1$IC/mod3$IC-1
df$sw2<-mod2$IC/mod3$IC-1
df$sw4<-mod4$IC/mod3$IC-1
df$sw5<-mod5$IC/mod3$IC-1

df<-df[,-1]
newdf<-reshape2::melt(df, id.var="time")
plot1<-ggplot()+geom_line(newdf, mapping=aes(time, value, color=variable, linetype=variable),linewidth=1.2)+ 
  scale_color_manual(values=c("#542788","#8073ac","#b35806","#7f3b08"))+ scale_linetype_manual(values=c("solid","solid","solid","solid"))+
  scale_x_continuous(breaks=c(0,50,100))+
  scale_y_continuous(labels=scales::percent, limits=c(-0.5,0.5))+geom_hline(yintercept=0, linetype="dashed",color="gray", linewidth=1)+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=12))+xlab("Time(Day)")+ylab("Respiration")
plot1

pdf("open_sensitivity_ICnew.pdf",width=3.8, height=2.5)
plot1
dev.off()

#-----sensitivity plot-------

df<-data.frame(matrix(NA, nrow=nrow(mod1)))
df$time<-mod1$Time
df$sw1<-mod1$SC/1000
df$sw2<-mod2$SC/1000
df$sw3<-mod3$SC/1000
df$sw4<-mod4$SC/1000
df$sw5<-mod5$SC/1000

df<-df[,-1]
newdf<-reshape2::melt(df, id.var="time")
plot1<-ggplot()+geom_line(newdf, mapping=aes(time, value, color=variable, linetype=variable),linewidth=1.2)+ 
  scale_color_manual(values=c("#542788","#8073ac","gray","#b35806","#7f3b08"))+ scale_linetype_manual(values=c("solid","solid","dashed","solid","solid"))+
  scale_x_continuous(breaks=c(0,50,100))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=12))+xlab("Time(Day)")+ylab("SC (dS/m)")
plot1

pdf("closed_sensitivity_SCnew.pdf",width=3.5, height=2.5)
plot1
dev.off()


#---area graph of carbon flux------

mod1<-read.delim("fixp_redox_sw4.txt",header=TRUE)
mod1<-mod1[-1, ]

df<-data.frame(matrix(NA, nrow=nrow(mod1)))
df$time<-mod1$Time
df$Aero<-mod1$Caero
df$SulR<-mod1$Csulr
df$xMeth<-mod1$Cmeth
df<-df[,-1]
df<-df[-1 ,]

test<-df[1:100, ]
newdf<-reshape2::melt(test, id.var="time")

library(dplyr)
library(viridis)
data <- newdf  %>%
  group_by(time, variable) %>%
  summarise(n = sum(value)) %>%
  mutate(percentage = n / sum(n))


plot1<-ggplot(data, aes(x=time, y=percentage, fill=variable)) + 
    geom_area(alpha=0.6,linewidth=1.5, colour="white")+scale_y_continuous(labels=scales::percent)+ scale_fill_manual(values=c("#b35806","#fdb863","#542788"))+ theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=8))+xlab("Time(Day)")+ylab("Carbon flux")
plot1

pdf("open_sw4.pdf",width=3.2, height=2)
plot1
dev.off()

#------
plot1<-ggplot()+geom_boxplot(obv, mapping=aes(x=time, y=IC, group=time), color="black", alpha=0.2, width=16)+ 
  scale_x_continuous(breaks=c(0,200,400))+
  #scale_y_continuous(limits=c(-0.02,0.02), breaks=c(-0.1,0,0.1))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=10))+xlab("Time(Day)")+ylab("IC")

pdf("Rsalt_obv_label.pdf",width=4, height=3)
plot1
dev.off()

#-----anova---
df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$fs1<-fs1$IC
df$fs2<-fs2$IC
df$fs3<-fs3$IC
df$fs4<-fs4$IC
df<-df[,-1]

#---select rows based on values in a vector
df<-df[df$time %in% obv$time, ]

newdf<-reshape2::melt(df, id.var="time")

obv<-read.csv("Ultisol_control.csv")
obv$variable<- c("o")
obv<-obv[,c("time","variable","IC")]
colnames(obv)<-c("time","variable","value")


test<-rbind(newdf, obv)
test<-test[,-1]

sub1<-test[test$variable %in% c("fs3",'o'), ]
fm1<-aov(value~variable, data=sub1)
anova(fm1)

TukeyHSD(fm1, conf.level=.95) 

plot(TukeyHSD(fm1, conf.level=.95), las = 2)




df<-data.frame(matrix(NA, nrow=401))
df$time<-mod1$Time
df$lwr<-mod1$IC/ref$IC-1
df$ref<-mod2$IC/ref$IC-1
df$upr<-mod3$IC/ref$IC-1
df<-df[,-1]



plot1<-ggplot()+ theme_pubr(border=TRUE)+theme(legend.position="right")+theme(strip.text=element_text(size=18, face="bold"))+xlab("Time(Day)")+ylab("IC change")+scale_y_continuous(labels = scales::percent)

plot2<-plot1+
  geom_line(data=df, mapping=aes(x=time, y=ref),color="#b35806",linewidth=1.2 )+geom_ribbon(data=df, aes(x=time, ymin=lwr, ymax=upr), alpha=0.3,inherit.aes=F, fill="#b35806" )


plot2

pdf("owc_wetlandSC.pdf",width=3.5, height=2.5)
plot3
dev.off()

##------response ratio plot 

ctrl<-read.delim("fixp_redox_sw3.txt",header=TRUE)
fs1<-read.delim("fixp_redox_sw1.txt",header=TRUE)
fs2<-read.delim("fixp_redox_sw2.txt",header=TRUE)
fs3<-read.delim("fixp_redox_sw4.txt",header=TRUE)
fs4<-read.delim("fixp_redox_sw5.txt",header=TRUE)
#obv<-read.csv("Ultisol_control_gram.csv")
#mend<-read.csv("Ul_test.csv")
##--------simple data visualization
ctrl<-ctrl[-(1:2), ]
fs1<-fs1[-(1:2), ]
fs2<-fs2[-(1:2), ]
fs3<-fs3[-(1:2), ]
fs4<-fs4[-(1:2), ]

ctrl<- ctrl[, !names(ctrl) %in% c("mu","pH.1", "FeS", "Calcite","X")]
fs1<- fs1[, !names(fs1) %in% c("mu","pH.1", "FeS", "Calcite","X")]
fs2<- fs2[, !names(fs2) %in% c("mu","pH.1", "FeS", "Calcite","X")]
fs3<- fs3[, !names(fs3) %in% c("mu","pH.1", "FeS", "Calcite","X")]
fs4<- fs4[, !names(fs4) %in% c("mu","pH.1", "FeS", "Calcite","X")]

#take 1 year % change---response ratio

fs1sum<-log(fs1[50,])-log(ctrl[50,])
fs2sum<-log(fs2[50,])-log(ctrl[50,])
fs3sum<-log(fs3[50,])-log(ctrl[50,])
fs4sum<-log(fs4[50,])-log(ctrl[50,])


fs1sum$lab<-c("C1")
fs2sum$lab<-c("C2")
fs3sum$lab<-c("C3")
fs4sum$lab<-c("C4")


sum<-rbind(fs1sum, fs2sum, fs3sum, fs4sum)


group1 <- sum[, c("lab","Na","K", "Ca","Mg", "Cl","SO4","HS","NH4","Ozero","SC","pH")]
colnames(group1)<-c("lab","Na","K", "Ca","Mg", "Cl","SO4","HS","NH4","DO","SC","pH")
newg1<-reshape2::melt(group1, id.var="lab")


group2 <- sum[, c("lab","MOM","POM","QOM","DOM","OrgAcid","BA","EP","EM","IC","CH4","Total")]
colnames(group2)<-c("lab","MOM","POM","DOMs","DOM","OA","BA","EP","EM","IC","CH4","Total")
newg2<-reshape2::melt(group2, id.var="lab")
#newg1$sign<-c("pos")
#newg1[19, 4]<-c("neg")
#newg1[20, 4]<-c("neg")



plot1<-ggplot()+geom_bar(newg2, mapping=aes(x=value, y=variable, fill=lab), stat="identity", position="dodge")+
  scale_fill_brewer(palette="PuOr")+
  #cale_fill_manual(values=c("#b35806","#fdb863","#b2abd2","#542788"))+ #scale_x_continuous(limits=c(-3,9), breaks=c(-3, 0, 3, 6, 9))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=10))
plot1

pdf("open_redox-group2.pdf",width=3.5, height=4.5)
plot1
dev.off()

plot2<-ggplot()+geom_bar(newg2, mapping=aes(x=value, y=variable, fill=lab), stat="identity", position="dodge")+ 
 scale_fill_manual(values=c("#e08214","#b2abd2"))+ 
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=10))
plot2

pdf("tempest-legend.pdf",width=4, height=4)
plot2
dev.off()



```


###testing pe

```{r petest}

ctrl<-read.delim("closed_redox_petest.txt",header=TRUE)

##--------simple data visualization
ctrl<-ctrl[-(1:2), ]
test1<-ctrl[, (1:10)]


plot1<-ggplot()+geom_point(ctrl, mapping=aes(x=Time, y=CO2), color="#b35806")+scale_fill_brewer(palette="PuOr")+
  #cale_fill_manual(values=c("#b35806","#fdb863","#b2abd2","#542788"))+ #scale_x_continuous(limits=c(-3,9), breaks=c(-3, 0, 3, 6, 9))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=10))+xlab("Time(Day)")+ylab("pH")
plot1

pdf("test_pH.pdf",width=3.5, height=3)
plot1
dev.off()

plot2<-ggplot()+geom_bar(newg2, mapping=aes(x=value, y=variable, fill=lab), stat="identity", position="dodge")+ 
 scale_fill_manual(values=c("#e08214","#b2abd2"))+ 
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=10))
plot2

pdf("tempest-legend.pdf",width=4, height=4)
plot2
dev.off()



```


```{r sensitivity}

df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$fs1<-fs1$BA/ctrl$BA-1
df$fs2<-fs2$BA/ctrl$BA-1
df$fs3<-fs3$BA/ctrl$BA-1
df$fs4<-fs4$BA/ctrl$BA-1

df<-df[,-1]
newdf<-reshape2::melt(df, id.var="time")

plot1<-ggplot()+geom_line(newdf, mapping=aes(time, value, color=variable),linewidth=1)+ 
  scale_color_manual(values=c("#542788","#8073ac","#b35806","#7f3b08"))+ 
  geom_hline(yintercept=0, linetype="dashed")+
  scale_y_continuous(labels=percent)+
  scale_x_continuous(breaks=c(0,200,400))+
  theme_pubr(border=TRUE)+theme(legend.position="right")+
  theme(text=element_text(size=10))+
  xlab("Time(Day)")+
  ylab("Biomass")
plot3<-plot1+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs1, ymax=fs2), fill="#b2abd2", alpha=0.5)
plot4<-plot3+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs3, ymax=fs4), fill="#b35806", alpha=0.3)


pdf("Brazil_fsal_Ex_mb_Biomass.pdf",width=3.8, height=2.5)
plot4
dev.off()

#----
df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$fs1<-(fs1$DOM+fs1$QOM)/(ctrl$DOM+ctrl$QOM)-1
df$fs2<-(fs2$DOM+fs2$QOM)/(ctrl$DOM+ctrl$QOM)-1
df$fs3<-(fs3$DOM+fs3$QOM)/(ctrl$DOM+ctrl$QOM)-1
df$fs4<-(fs4$DOM+fs4$QOM)/(ctrl$DOM+ctrl$QOM)-1


df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$fs1<-fs1$DOM/ctrl$DOM-1
df$fs2<-fs2$DOM/ctrl$DOM-1
df$fs3<-fs3$DOM/ctrl$DOM-1
df$fs4<-fs4$DOM/ctrl$DOM-1


df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$fs1<-fs1$QOM/ctrl$QOM-1
df$fs2<-fs2$QOM/ctrl$QOM-1
df$fs3<-fs3$QOM/ctrl$QOM-1
df$fs4<-fs4$QOM/ctrl$QOM-1

df<-df[,-1]
newdf<-reshape2::melt(df, id.var="time")

plot1<-ggplot()+geom_line(newdf, mapping=aes(time, value, color=variable),linewidth=1)+ 
  scale_color_manual(values=c("#542788","#8073ac","#b35806","#7f3b08"))+ geom_hline(yintercept=0, linetype="dashed")+
   scale_y_continuous(labels=percent)+
  scale_x_continuous(breaks=c(0,200,400))+
  theme_pubr(border=TRUE)+theme(legend.position="right")+
  theme(text=element_text(size=10))+
  xlab("Time(Day)")+
  ylab("DOM")
plot3<-plot1+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs1, ymax=fs2), fill="#b2abd2", alpha=0.5)
plot4<-plot3+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs3, ymax=fs4), fill="#b35806", alpha=0.3)

pdf("Brazil_fsal_Ex_mb_DQOM.pdf",width=3.8, height=2.5)
plot4
dev.off()


#----
df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$fs1<-fs1$Total/ctrl$Total-1
df$fs2<-fs2$Total/ctrl$Total-1
df$fs3<-fs3$Total/ctrl$Total-1
df$fs4<-fs4$Total/ctrl$Total-1
#----
df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$fs1<-(fs1$EM+fs1$EP)/(ctrl$EM+ctrl$EP)-1
df$fs2<-(fs2$EM+fs2$EP)/(ctrl$EM+ctrl$EP)-1
df$fs3<-(fs3$EM+fs3$EP)/(ctrl$EM+ctrl$EP)-1
df$fs4<-(fs4$EM+fs4$EP)/(ctrl$EM+ctrl$EP)-1


df<-df[,-1]
newdf<-reshape2::melt(df, id.var="time")

plot1<-ggplot()+geom_line(newdf, mapping=aes(time, value, color=variable),linewidth=1)+ 
  scale_color_manual(values=c("#542788","#8073ac","#b35806","#7f3b08"))+ 
  geom_hline(yintercept=0, linetype="dashed")+   
  scale_y_continuous(labels=percent)+
  scale_x_continuous(breaks=c(0,200,400))+
  theme_pubr(border=TRUE)+theme(legend.position="right")+
  theme(text=element_text(size=10))+
  xlab("Time(Day)")+
  ylab("EM+EP")

plot3<-plot1+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs1, ymax=fs2), fill="#b2abd2", alpha=0.5)
plot4<-plot3+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs3, ymax=fs4), fill="#b35806", alpha=0.3)

pdf("Brazil_fsal_Ex_mb_Enzymes.pdf",width=3.8, height=2.5)
plot4
dev.off()


#----
df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$SC<-ctrl$SC/1000

plot1<-ggplot()+geom_line(df, mapping=aes(time, SC),linewidth=1, color="#542788")+ 
  scale_x_continuous(breaks=c(0,200,400))+
  theme_pubr(border=TRUE)+theme(legend.position="right")+
  theme(text=element_text(size=12))+
  xlab("Time(Day)")+
  ylab("SC (dS/m)")
pdf("Brazil_fsal_SC.pdf",width=2.2, height=2)
plot1
dev.off()

#----


```



##load data
```{r data}

fresh<-read.csv("clay_fresh.csv",header=TRUE)
fresh$time<-c(6,19,33,47,62,75,89,103,117,131,145,159,173,187,201)

salt<-read.csv("clay_salt.csv",header=TRUE)
salt$time<-c(6,19,33,47,62,75,89,103,117,131,145,159,173,187,201)

mod1<-read.delim("vanD_clay_fresh_low.txt",header=TRUE)
mod1<-mod1[-1, ]

mod2<-read.delim("vanD_clay_fresh_ref.txt",header=TRUE)
mod2<-mod2[-1, ]

mod3<-read.delim("vanD_clay_fresh_high.txt",header=TRUE)
mod3<-mod3[-1, ]



salt1<-read.delim("vanD_clay_salt_low.txt",header=TRUE)
salt1<-salt1[-1, ]

salt2<-read.delim("vanD_clay_salt_ref.txt",header=TRUE)
salt2<-salt2[-1, ]

salt3<-read.delim("vanD_clay_salt_high.txt",header=TRUE)
salt3<-salt3[-1, ]

ctf<-read.delim("vanD_clay_fresh_ctrl.txt",header=TRUE)
ctf<-ctf[-1, ]
cts<-read.delim("vanD_clay_salt_ctrl.txt",header=TRUE)
cts<-cts[-1, ]


df<-data.frame(matrix(NA, nrow=15))
df$time<-fresh$time
df$lwr<-mod1$PO4*1000
df$ref<-mod2$PO4*1000
df$upr<-mod3$PO4*1000
df<-df[,-1]



ds<-data.frame(matrix(NA, nrow=15))
ds$time<-salt$time
ds$lwr<-salt1$PO4*1000
ds$ref<-salt2$PO4*1000
ds$upr<-salt3$PO4*1000
ds<-ds[,-1]


obv<-data.frame(matrix(NA, nrow=15))
obv$time<-fresh$time
obv$fresh<-fresh$PO4
obv$salt<-salt$PO4
obv<-obv[,-1]

obvdf<-reshape2::melt(obv, id.var="time")


ctrl<-data.frame(matrix(NA, nrow=15))
ctrl$time<-fresh$time
ctrl$fresh<-ctf$PO4*1000
ctrl$salt<-cts$PO4*1000
ctrl<-ctrl[,-1]

ctdf<-reshape2::melt(ctrl, id.var="time")


plot1<-ggplot()+geom_point(obvdf, mapping=aes(time, value, color=variable), size=2)+
 scale_y_continuous(limits=c(0,0.2), breaks=c(0,0.1,0.2))+
  scale_x_continuous(limits=c(0,205), breaks=c(0,100,200))+
 scale_color_manual(values = c("#b35806","#8073ac"))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(strip.text=element_text(size=18, face="bold"))+xlab("Time(Day)")+ylab("Ptot (mM)")

plot2<-plot1+
  geom_line(data=df, mapping=aes(x=time, y=ref),color="#b35806",linewidth=1.2 )+geom_ribbon(data=df, aes(x=time, ymin=lwr, ymax=upr), alpha=0.3,inherit.aes=F, fill="#b35806" )

plot3<-plot2+
  geom_line(data=ds, mapping=aes(x=time, y=ref),color="#8073ac",linewidth=1.2 )+geom_ribbon(data=ds, aes(x=time, ymin=lwr, ymax=upr), alpha=0.3,inherit.aes=F, fill="#8073ac" )

plot4<-plot3+geom_line(data=ctdf, mapping=aes(x=time, y=value, color=variable),linetype="dashed",linewidth=1 )
plot4



pdf("clay_P.pdf",width=3.8, height=2.5)
plot4
dev.off()



#------------------

df<-data.frame(matrix(NA, nrow=15))
df$time<-fresh$time
df$lwr<-mod1$pH
df$ref<-mod2$pH
df$upr<-mod3$pH
df<-df[,-1]



ds<-data.frame(matrix(NA, nrow=15))
ds$time<-salt$time
ds$lwr<-salt1$pH
ds$ref<-salt2$pH
ds$upr<-salt3$pH
ds<-ds[,-1]


obv<-data.frame(matrix(NA, nrow=15))
obv$time<-fresh$time
obv$fresh<-fresh$pH
obv$salt<-salt$pH
obv<-obv[,-1]

obvdf<-reshape2::melt(obv, id.var="time")


ctrl<-data.frame(matrix(NA, nrow=15))
ctrl$time<-fresh$time
ctrl$fresh<-ctf$pH
ctrl$salt<-cts$pH
ctrl<-ctrl[,-1]

ctdf<-reshape2::melt(ctrl, id.var="time")


plot1<-ggplot()+geom_point(obvdf, mapping=aes(time, value, color=variable), size=2)+
scale_y_continuous(limits=c(6,10), breaks=c(6,8,10))+
  scale_x_continuous(limits=c(0,205), breaks=c(0,100,200))+
 scale_color_manual(values = c("#b35806","#8073ac"))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(strip.text=element_text(size=18, face="bold"))+xlab("Time(Day)")+ylab("pH")

plot2<-plot1+
  geom_line(data=df, mapping=aes(x=time, y=ref),color="#b35806",linewidth=1.2 )+geom_ribbon(data=df, aes(x=time, ymin=lwr, ymax=upr), alpha=0.3,inherit.aes=F, fill="#b35806" )

plot3<-plot2+
  geom_line(data=ds, mapping=aes(x=time, y=ref),color="#8073ac",linewidth=1.2 )+geom_ribbon(data=ds, aes(x=time, ymin=lwr, ymax=upr), alpha=0.3,inherit.aes=F, fill="#8073ac" )

plot4<-plot3+geom_line(data=ctdf, mapping=aes(x=time, y=value, color=variable),linetype="dashed",linewidth=1 )
plot4



pdf("clay_pH.pdf",width=3.8, height=2.5)
plot4
dev.off()



```

##graph all soils
```{r plot}

Ul<-read.csv("Ultisol_control.csv",header=TRUE)
Ge<-read.csv("Gelisol_control.csv",header=TRUE)
Mo<-read.csv("Mollisol_control.csv",header=TRUE)
An<-read.csv("Andisol_control.csv",header=TRUE)

SUl<-read.csv("Ultisol_simulations.csv",header=TRUE)
SGe<-read.csv("Gelisol_simulations.csv",header=TRUE)
SMo<-read.csv("Mollisol_simulations.csv",header=TRUE)
SAn<-read.csv("Andisol_simulations.csv",header=TRUE)



pdf("4soils.pdf", width=6, height=4)
par(xpd = T, mar = par()$mar + c(0,0,0,10))
plot(Ul$time,Ul$IC/23.484, xlab = "Time (d)", ylab = "Respiration (mgC g-1 C)", pch=16, cex=1.2,col="#b35806", xlim=c(0,400), ylim=c(0,0.2),cex.lab=1.2, cex.axis=1.2)
lines(SUl$time,SUl$IC/23.484, lwd=2, col="#b35806")
points(Mo$time,Mo$IC/32.198, pch=16, cex=1.2, col="#fdb863")
lines(SMo$time,SMo$IC/32.198, lwd=2, col="#fdb863")
points(An$time,An$IC/86.592, pch=16, cex=1.2, col="#b2abd2")
lines(SAn$time,SAn$IC/86.592, lwd=2, col="#b2abd2")
points(Ge$time,Ge$IC/15.52, pch=16, cex=1.2, col="#542788")
lines(SGe$time,SGe$IC/15.52, lwd=2, col="#542788")


legend("topright",inset = c(- 0.6, 0), c("Tropical","Temperate","Subarctic","Arctic"), lwd=2, lty=1,col=c("#b35806","#fdb863","#b2abd2","#542788"))


dev.off()


pdf("test.pdf", width=6, height=4)
plot(SUl$time,SUl$MOM/23.484, lwd=2, col="#b35806",xlim=c(0,400), ylim=c(0,1))
points(SMo$time,SMo$MOM/32.198, lwd=2, col="#fdb863")
points(SAn$time,SAn$MOM/86.592, lwd=2, col="#b2abd2")
points(SGe$time,SGe$MOM/15.52, lwd=2, col="#542788")
legend("topright",inset = c(- 0.6, 0), c("Tropical","Temperate","Sub-arctic","Arctic"), lwd=2, lty=1,col=c("#b35806","#fdb863","#b2abd2","#542788"))
dev.off

```

##
```{R plot}
pool<-read.csv("Poolsize2.csv")
p1<-ggplot(pool, aes(x=sample, y=value,fill=sample, color=sample))+geom_bar( stat="identity",size=0.08)+ #geom_smooth(aes(fill=series),alpha=0.2)+
  facet_wrap(~fraction)+
scale_fill_manual(values=c("#b35806","#fdb863","#b2abd2","#542788"))+
scale_color_manual(values=c('white','white','white','white'))+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=10))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 10, colour = "black"),axis.text.x=element_text(angle =45, vjust = 0.5))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1
pdf("poolsize2.pdf",width=4, height=2)
p1
dev.off()
```


```{R plot}
pool<-read.csv("nutnet.csv")
pw<-data.frame(pH=pool$Obv)
pw$no<-pool$No_OL
pw$om<-pool$OL
pw<-melt(pw, id.var=c("pH"))

# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pw, aes(x=pH, y=value, color=variable))+geom_point()+ 
  geom_smooth(method=lm, aes(fill=variable))+scale_color_manual(values=c("#8073ac","#b35806"))+
scale_fill_manual(values=c("#8073ac","#b35806"))+ scale_x_continuous(name = 'Observed pH',labels=scaleFUN) + scale_y_continuous(name = 'Predicted pH',labels=scaleFUN)+ geom_abline(intercept=0,slope=1, color="black", linetype="dashed")+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=14))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 14, colour = "black"))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("nutnetpH.pdf",width=4, height=2.5)
p1
dev.off()
```


```{R plot}
pka<-read.csv("pKas.csv")

# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pka, aes(x=pKa))+geom_histogram(binwidth=1,color="#b35806", fill="white")+ scale_y_continuous(name = 'Frequency')+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=16))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 16, colour = "black"))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("pKa.pdf",width=4, height=2.5)
p1
dev.off()
```

##pH sensitivity of exoenzymes
```{R plot}
pool<-read.csv("Cellobiohydrolase.csv")
# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pool, aes(x=pH, y=Activity))+geom_point(color="#b35806")+ 
  geom_smooth(method=loess, color="#b35806", fill="#b35806")+geom_vline(xintercept=7,color="black", linetype="dashed")+geom_vline(xintercept=6,color="black", linetype="dashed")+geom_vline(xintercept=5,color="black", linetype="dashed")+geom_vline(xintercept=4,color="black", linetype="dashed")+
scale_x_continuous(name = 'Observed pH',limits=c(2,12), breaks=c(2,4,6,8,10,12)) + scale_y_continuous(name = 'Relative activity',labels=scaleFUN)+ 
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=12))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 12, colour = "black"))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("CellopH.pdf",width=3, height=2)
p1
dev.off()
```



##soil pH 
```{R plot}
pool<-read.csv("soilph.csv")


# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pool, aes(x=pH, y=value, color=soil))+geom_point()+ 
  geom_smooth(method=loess,aes(fill=NA))+scale_color_manual(values=c("#b2abd2","#8073ac","#542788"))+
scale_fill_manual(values=c("#b2abd2","#8073ac","#542788"))+ scale_x_continuous(name = 'Observed pH',limits=c(2,12), breaks=c(2,4,6,8,10,12)) + scale_y_continuous(name = 'Relative activity',labels=scaleFUN)+ geom_vline(xintercept=7,color="black", linetype="dashed")+geom_vline(xintercept=6,color="black", linetype="dashed")+geom_vline(xintercept=5,color="black", linetype="dashed")+geom_vline(xintercept=4,color="black", linetype="dashed")+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=12))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 12, colour = "black"))+theme(legend.position="none")#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("soilpH.pdf",width=3, height=2)
p1
dev.off()
```

##soil pH 
```{R plot}
def1<-read.csv("def1.csv")
def2<-read.csv("def2.csv")
def3<-read.csv("def3.csv")
def4<-read.csv("def4.csv")
def5<-read.csv("def5.csv")

test<-rbind(def1, def2, def3, def4, def5)


# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(test, aes(x=mu, y=pH, color=level))+geom_point()+ 
  geom_smooth(method=loess,aes(fill=NA))+scale_color_manual(values=c("#fee0b6","#fdb863","#e08214","#b35806","#7f3b08"))+geom_hline(yintercept=5.42,color="black", linetype="dashed")+
scale_fill_manual(values=c("#fee0b6","#fdb863","#e08214","#b35806","#7f3b08"))+ scale_x_continuous(name = 'Ionic strength (mmol/L)') + scale_y_continuous(name = 'pH',labels=scaleFUN)+ 
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=14))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 14, colour = "black"))+theme(legend.position="none")#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("muPH.pdf",width=4, height=2.5)
p1
dev.off()
```


```{r fph}
#====pH response function====
pH<-seq(2,12,0.01)
fpHref<-10^(-0.2235*pH^2+2.7727*pH -8.6)
f3<-fpHref/max(fpHref)

f2<-(pH-4)*(pH-10)/((pH-4)*(pH-10)-(pH-7)^2)

ph1<-seq(2,7,0.01)
fph1<-1.02/(1.02+10^6*exp(-2.5*ph1))
ph2<-seq(7.01,12,0.01)
fph2<-1.02/(1.02+10^6*exp(-2.5*(14-ph2)))

data1<-data.frame(pH=ph1)
data1$fpH1<-fph1

data2<-data.frame(pH=ph2)
data2$fpH1<-fph2

allf<-rbind(data1, data2)
allf$fpH2<-f2
allf$fpH3<-f3

fpHs<-melt(allf, id.var=c("pH"))

plot1<-ggplot(fpHs, aes(x = pH,y = value, color=variable)) +
  scale_x_continuous(name = 'pH', breaks=c(0,2,4,6,8,10,12,14)) +
  scale_y_continuous(name = 'Relative activity', limits=c(0,1)) + geom_line(aes(color=variable),size=1)+
  scale_color_manual(values =c("#fee0b6","#e08214","#7f3b08"))
plot2<-plot1+theme_linedraw()+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=14))
plot2

pdf("fpH.pdf",width=5, height=2.8)
plot2
dev.off()
```


##Supplement figure---sensitivity test---adding small salinity and fsal---impact of solution chemistry and pools

```{r data}
ctrl<-read.delim("Rsalt_Ex_ref.txt",header=TRUE)
fs1<-read.delim("Rsalt_Ex_salttest1_pom.txt",header=TRUE)
fs2<-read.delim("Rsalt_Ex_salttest2_pom.txt",header=TRUE)
fs3<-read.delim("Rsalt_Ex_salttest3_pom.txt",header=TRUE)
fs4<-read.delim("Rsalt_Ex_salttest4_pom.txt",header=TRUE)
#obv<-read.csv("Ultisol_control_gram.csv")
#mend<-read.csv("Ul_test.csv")
##--------simple data visualization
ctrl<-ctrl[-(1:2), ]
fs1<-fs1[-(1:2), ]
fs2<-fs2[-(1:2), ]
fs3<-fs3[-(1:2), ]
fs4<-fs4[-(1:2), ]

ctrl<- ctrl[, !names(ctrl) %in% c("mu","pH.1", "FeS", "Calcite","X")]
fs1<- fs1[, !names(fs1) %in% c("mu","pH.1", "FeS", "Calcite","X")]
fs2<- fs2[, !names(fs2) %in% c("mu","pH.1", "FeS", "Calcite","X")]
fs3<- fs3[, !names(fs3) %in% c("mu","pH.1", "FeS", "Calcite","X")]
fs4<- fs4[, !names(fs4) %in% c("mu","pH.1", "FeS", "Calcite","X")]

#take 1 year % change---response ratio

fs1sum<-log(fs1[365,])-log(ctrl[365,])
fs2sum<-log(fs2[365,])-log(ctrl[365,])
fs3sum<-log(fs3[365,])-log(ctrl[365,])
fs4sum<-log(fs4[365,])-log(ctrl[365,])

fs1sum$lab<-c("salt1")
fs2sum$lab<-c("salt2")
fs3sum$lab<-c("salt3")
fs4sum$lab<-c("salt4")

sum<-rbind(fs1sum, fs2sum, fs3sum, fs4sum)

group1 <- sum[, c("lab","pH","Na","K", "Ca","Mg", "Cl","HCO3","SO4","PO4","NH4")]
newg1<-reshape2::melt(group1, id.var="lab")



group2 <- sum[, c("lab","MOM","POM","QOM", "DOM","BA", "EP","EM","IC","Total","SC")]
newg2<-reshape2::melt(group2, id.var="lab")



plot1<-ggplot()+geom_bar(newg1, mapping=aes(x=value, y=variable, fill=lab), stat="identity", position="dodge")+ 
  scale_fill_brewer(palette = "PuOr")+ scale_x_continuous(limits=c(-3,9), breaks=c(-3, 0, 3, 6, 9))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=10))
plot1

pdf("salttest-group1_pom.pdf",width=3.5, height=4)
plot1
dev.off()

plot2<-ggplot()+geom_bar(newg2, mapping=aes(x=value, y=variable, fill=lab), stat="identity", position="dodge")+ 
  scale_fill_brewer(palette = "PuOr")+ 
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=10))
plot2

pdf("salttest-group2_pom.pdf",width=3.5, height=4)
plot2
dev.off()


plot2<-plot1+geom_boxplot(obv, mapping=aes(x=time, y=IC, group=time), color="black", alpha=0.2, width=16)
plot3<-plot2+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs1, ymax=fs2), fill="#b2abd2", alpha=0.5)
plot4<-plot3+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs3, ymax=fs4), fill="#b35806", alpha=0.3)
plot4 


pdf("Ex3_IC_obv.pdf",width=2.2, height=2)
plot4
dev.off()



```



