---
title: "MENDsimulations"
author: "Jianqiu Zheng"
date: "7/15/2021"
output: html_document
---



```{r setup, include=FALSE}
library(ggplot2)
library(ggpubr)
library(scales)
library(MASS) # to access Animals data sets
library(ggallin)
library(dplyr)
library(readr)
library(tidyr)
library(stringr)
library(ggpmisc)
theme_pubr()
```

##Figure 1 Comparing effect of 3 exchange component

```{r data}
ctrl<-read.delim("Rsalt_ref.txt",header=TRUE)
fs1<-read.delim("Ex1_ref_f1.txt",header=TRUE)
fs2<-read.delim("Ex1_sorp_f1.txt",header=TRUE)
fs3<-read.delim("Rsalt_ref_Ex1_sorp_f3.txt",header=TRUE)
fs4<-read.delim("Rsalt_ref_Ex1_sorp_f4.txt",header=TRUE)
obv<-read.csv("Ultisol_control.csv")
##--------simple data visualization
ctrl<-ctrl[-(1:2), ]
fs1<-fs1[-(1:2), ]
fs2<-fs2[-(1:2), ]
fs3<-fs3[-(1:2), ]
fs4<-fs4[-(1:2), ]

df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$fs1<-fs1$IC
df$fs2<-fs2$IC
df$fs3<-fs3$IC
df$fs4<-fs4$IC

df<-df[,-1]
newdf<-reshape2::melt(df, id.var="time")


plot1<-ggplot()+geom_line(newdf, mapping=aes(time, value, color=variable, linetype=variable),linewidth=0.5)+ 
  scale_color_manual(values=c("#542788","#8073ac","#b35806","#7f3b08"))+ scale_linetype_manual(values=c("solid","solid","solid","solid"))+
  scale_x_continuous(breaks=c(0,200,400))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=12))+xlab("Time(Day)")+ylab("IC")
plot2<-plot1+geom_boxplot(obv, mapping=aes(x=time, y=IC, group=time), color="black", alpha=0.2, width=16)
plot3<-plot2+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs1, ymax=fs2), fill="#b2abd2", alpha=0.5)
plot4<-plot3+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs3, ymax=fs4), fill="#b35806", alpha=0.3)
plot4 


pdf("Rsalt_Ex3_lowSB_IC_obv.pdf",width=3.5, height=2.5)
plot4
dev.off()
#-----testing salinity response-------

df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$fs1<-1/(fs1$fsl1)
df$fs2<-1/(fs2$fsl2)
df$fs3<-1/(fs3$fsl3)
df$fs4<-1/(fs4$fsl4)

df<-df[,-1]
newdf<-reshape2::melt(df, id.var="time")
plot1<-ggplot()+geom_line(newdf, mapping=aes(time, value, color=variable, linetype=variable),linewidth=0.5)+ 
  scale_color_manual(values=c("#542788","#8073ac","#b35806","#7f3b08"))+ scale_linetype_manual(values=c("solid","solid","solid","solid"))+
  scale_x_continuous(breaks=c(0,200,400))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=10))+xlab("Time(Day)")+ylab("IC")



#---legend------

df=data.frame(x = seq(0, 3, by=1))
df$y1<-1
df$y2<-2
df$y3<-4
df$y4<-5
newdf<-reshape2::melt(df, id.var="x")

plot1<-ggplot()+geom_line(newdf, mapping=aes(x, value, color=variable, linetype=variable),linewidth=1)+ 
  scale_color_manual(values=c("#542788","#8073ac","#b35806","#7f3b08"))+     scale_linetype_manual(values=c("solid","solid","solid","solid"))+
  scale_y_continuous(limits=c(0,15))+
  #scale_y_continuous(limits=c(-0.02,0.02), breaks=c(-0.1,0,0.1))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=10))

plot3<-plot1+geom_ribbon(data=df, mapping=aes(x=x, ymin=y1, ymax=y2), fill="#b2abd2", alpha=0.5)
plot4<-plot3+geom_ribbon(data=df, mapping=aes(x=x, ymin=y3, ymax=y4), fill="#b35806", alpha=0.3)
  
pdf("Rsalt_sensitivity_label.pdf",width=3.5, height=2.5)
plot4
dev.off()

#------
plot1<-ggplot()+geom_boxplot(obv, mapping=aes(x=time, y=IC, group=time), color="black", alpha=0.2, width=16)+ 
  scale_x_continuous(breaks=c(0,200,400))+
  #scale_y_continuous(limits=c(-0.02,0.02), breaks=c(-0.1,0,0.1))+
 theme_pubr(border=TRUE)+theme(legend.position="right")+theme(text=element_text(size=10))+xlab("Time(Day)")+ylab("IC")

pdf("Rsalt_obv_label.pdf",width=4, height=3)
plot1
dev.off()

#-----anova---
df<-data.frame(matrix(NA, nrow=nrow(ctrl)))
df$time<-ctrl$Time
df$fs1<-fs1$IC
df$fs2<-fs2$IC
df$fs3<-fs3$IC
df$fs4<-fs4$IC
df<-df[,-1]

#---select rows based on values in a vector
df<-df[df$time %in% obv$time, ]

newdf<-reshape2::melt(df, id.var="time")

obv<-read.csv("Ultisol_control.csv")
obv$variable<- c("o")
obv<-obv[,c("time","variable","IC")]
colnames(obv)<-c("time","variable","value")


test<-rbind(newdf, obv)
test<-test[,-1]

sub1<-test[test$variable %in% c("fs3",'o'), ]
fm1<-aov(value~variable, data=test)
anova(fm1)

TukeyHSD(fm1, conf.level=.95) 

plot(TukeyHSD(fm1, conf.level=.95), las = 2)

```


#
```{r data}
ctrl1<-read.delim("Ex3_ref_f1.txt",header=TRUE)
ctrl2<-read.delim("Ex3_ref_f2.txt",header=TRUE)
ctrl3<-read.delim("Ex3_ref_f3.txt",header=TRUE)
ctrl4<-read.delim("Ex3_ref_f4.txt",header=TRUE)


fs1<-read.delim("Ex3_both_f1.txt",header=TRUE)
fs2<-read.delim("Ex3_both_f2.txt",header=TRUE)
fs3<-read.delim("Ex3_both_f3.txt",header=TRUE)
fs4<-read.delim("Ex3_both_f4.txt",header=TRUE)


df<-data.frame(matrix(NA, nrow=nrow(ctrl1)))
df$time<-ctrl1$Time
df$fs1<-fs1$IC/ctrl1$IC-1
df$fs2<-fs2$IC/ctrl2$IC-1
df$fs3<-fs3$IC/ctrl3$IC-1
df$fs4<-fs4$IC/ctrl4$IC-1

df<-df[,-1]
newdf<-reshape2::melt(df, id.var="time")

plot1<-ggplot()+geom_line(newdf, mapping=aes(time, value, color=variable),linewidth=1)+ 
  scale_color_manual(values=c("#542788","#8073ac","#b35806","#7f3b08"))+ 
  geom_hline(yintercept=0, linetype="dashed")+
  scale_y_continuous(labels=percent, limits=(c(-0.05,0.05)), breaks=c(-0.05,-0.025,0,0.025,0.05))+
  scale_x_continuous(breaks=c(0,200,400))+
  theme_pubr(border=TRUE)+theme(legend.position="none")+
  theme(text=element_text(size=12))+theme(panel.grid.major.y = element_line(),
        panel.grid.minor.y = element_line())+
  xlab("Time(Day)")+
  ylab("Relative change")
plot3<-plot1+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs1, ymax=fs2), fill="#b2abd2", alpha=0.5)
plot4<-plot3+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs3, ymax=fs4), fill="#b35806", alpha=0.3)
plot4

pdf("Ex3_both_IC.pdf",width=2.9, height=2.5)
plot4
dev.off()

```



```{r data}
ctrl1<-read.delim("Ex1_ref_f1.txt",header=TRUE)
ctrl2<-read.delim("Ex1_ref_f2.txt",header=TRUE)
ctrl3<-read.delim("Ex1_ref_f3.txt",header=TRUE)
ctrl4<-read.delim("Ex1_ref_f4.txt",header=TRUE)


fs1<-read.delim("Ex1_agg_f1.txt",header=TRUE)
fs2<-read.delim("Ex1_agg_f2.txt",header=TRUE)
fs3<-read.delim("Ex1_agg_f3.txt",header=TRUE)
fs4<-read.delim("Ex1_agg_f4.txt",header=TRUE)


df<-data.frame(matrix(NA, nrow=nrow(ctrl1)))
df$time<-ctrl1$Time
df$fs1<-fs1$BA/ctrl1$BA-1
df$fs2<-fs2$BA/ctrl2$BA-1
df$fs3<-fs3$BA/ctrl3$BA-1
df$fs4<-fs4$BA/ctrl4$BA-1

df<-df[,-1]
newdf<-reshape2::melt(df, id.var="time")

plot1<-ggplot()+geom_line(newdf, mapping=aes(time, value, color=variable),linewidth=1)+ 
  scale_color_manual(values=c("#542788","#8073ac","#b35806","#7f3b08"))+ 
  geom_hline(yintercept=0, linetype="dashed")+
  #scale_y_continuous(labels=percent, limits=(c(-0.05,0.05)), breaks=c(-0.05,-0.025,0,0.025, 0.05))+
  scale_x_continuous(breaks=c(0,200,400))+
  theme_pubr(border=TRUE)+theme(legend.position="none")+
  theme(text=element_text(size=12))+
  xlab("Time(Day)")+
  ylab("Relative change")
plot3<-plot1+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs1, ymax=fs2), fill="#b2abd2", alpha=0.5)
plot4<-plot3+geom_ribbon(data=df, mapping=aes(x=time, ymin=fs3, ymax=fs4), fill="#b35806", alpha=0.3)
plot4

pdf("Ex1_agg_BA.pdf",width=2.9, height=2.5)
plot4
dev.off()

```



##graph all soils
```{r plot}

Ul<-read.csv("Ultisol_control.csv",header=TRUE)
Ge<-read.csv("Gelisol_control.csv",header=TRUE)
Mo<-read.csv("Mollisol_control.csv",header=TRUE)
An<-read.csv("Andisol_control.csv",header=TRUE)

SUl<-read.csv("Ultisol_simulations.csv",header=TRUE)
SGe<-read.csv("Gelisol_simulations.csv",header=TRUE)
SMo<-read.csv("Mollisol_simulations.csv",header=TRUE)
SAn<-read.csv("Andisol_simulations.csv",header=TRUE)



pdf("4soils.pdf", width=6, height=4)
par(xpd = T, mar = par()$mar + c(0,0,0,10))
plot(Ul$time,Ul$IC/23.484, xlab = "Time (d)", ylab = "Respiration (mgC g-1 C)", pch=16, cex=1.2,col="#b35806", xlim=c(0,400), ylim=c(0,0.2),cex.lab=1.2, cex.axis=1.2)
lines(SUl$time,SUl$IC/23.484, lwd=2, col="#b35806")
points(Mo$time,Mo$IC/32.198, pch=16, cex=1.2, col="#fdb863")
lines(SMo$time,SMo$IC/32.198, lwd=2, col="#fdb863")
points(An$time,An$IC/86.592, pch=16, cex=1.2, col="#b2abd2")
lines(SAn$time,SAn$IC/86.592, lwd=2, col="#b2abd2")
points(Ge$time,Ge$IC/15.52, pch=16, cex=1.2, col="#542788")
lines(SGe$time,SGe$IC/15.52, lwd=2, col="#542788")


legend("topright",inset = c(- 0.6, 0), c("Tropical","Temperate","Subarctic","Arctic"), lwd=2, lty=1,col=c("#b35806","#fdb863","#b2abd2","#542788"))


dev.off()


pdf("test.pdf", width=6, height=4)
plot(SUl$time,SUl$MOM/23.484, lwd=2, col="#b35806",xlim=c(0,400), ylim=c(0,1))
points(SMo$time,SMo$MOM/32.198, lwd=2, col="#fdb863")
points(SAn$time,SAn$MOM/86.592, lwd=2, col="#b2abd2")
points(SGe$time,SGe$MOM/15.52, lwd=2, col="#542788")
legend("topright",inset = c(- 0.6, 0), c("Tropical","Temperate","Sub-arctic","Arctic"), lwd=2, lty=1,col=c("#b35806","#fdb863","#b2abd2","#542788"))
dev.off

```

##
```{R plot}
pool<-read.csv("Poolsize2.csv")
p1<-ggplot(pool, aes(x=sample, y=value,fill=sample, color=sample))+geom_bar( stat="identity",size=0.08)+ #geom_smooth(aes(fill=series),alpha=0.2)+
  facet_wrap(~fraction)+
scale_fill_manual(values=c("#b35806","#fdb863","#b2abd2","#542788"))+
scale_color_manual(values=c('white','white','white','white'))+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=10))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 10, colour = "black"),axis.text.x=element_text(angle =45, vjust = 0.5))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1
pdf("poolsize2.pdf",width=4, height=2)
p1
dev.off()
```


```{R plot}
pool<-read.csv("nutnet.csv")
pw<-data.frame(pH=pool$Obv)
pw$no<-pool$No_OL
pw$om<-pool$OL
pw<-melt(pw, id.var=c("pH"))

# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pw, aes(x=pH, y=value, color=variable))+geom_point()+ 
  geom_smooth(method=lm, aes(fill=variable))+scale_color_manual(values=c("#8073ac","#b35806"))+
scale_fill_manual(values=c("#8073ac","#b35806"))+ scale_x_continuous(name = 'Observed pH',labels=scaleFUN) + scale_y_continuous(name = 'Predicted pH',labels=scaleFUN)+ geom_abline(intercept=0,slope=1, color="black", linetype="dashed")+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=14))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 14, colour = "black"))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("nutnetpH.pdf",width=4, height=2.5)
p1
dev.off()
```


```{R plot}
pka<-read.csv("pKas.csv")

# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pka, aes(x=pKa))+geom_histogram(binwidth=1,color="#b35806", fill="white")+ scale_y_continuous(name = 'Frequency')+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=16))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 16, colour = "black"))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("pKa.pdf",width=4, height=2.5)
p1
dev.off()
```

##pH sensitivity of exoenzymes
```{R plot}
pool<-read.csv("Cellobiohydrolase.csv")
# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pool, aes(x=pH, y=Activity))+geom_point(color="#b35806")+ 
  geom_smooth(method=loess, color="#b35806", fill="#b35806")+geom_vline(xintercept=7,color="black", linetype="dashed")+geom_vline(xintercept=6,color="black", linetype="dashed")+geom_vline(xintercept=5,color="black", linetype="dashed")+geom_vline(xintercept=4,color="black", linetype="dashed")+
scale_x_continuous(name = 'Observed pH',limits=c(2,12), breaks=c(2,4,6,8,10,12)) + scale_y_continuous(name = 'Relative activity',labels=scaleFUN)+ 
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=12))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 12, colour = "black"))#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("CellopH.pdf",width=3, height=2)
p1
dev.off()
```



##soil pH 
```{R plot}
pool<-read.csv("soilph.csv")


# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(pool, aes(x=pH, y=value, color=soil))+geom_point()+ 
  geom_smooth(method=loess,aes(fill=NA))+scale_color_manual(values=c("#b2abd2","#8073ac","#542788"))+
scale_fill_manual(values=c("#b2abd2","#8073ac","#542788"))+ scale_x_continuous(name = 'Observed pH',limits=c(2,12), breaks=c(2,4,6,8,10,12)) + scale_y_continuous(name = 'Relative activity',labels=scaleFUN)+ geom_vline(xintercept=7,color="black", linetype="dashed")+geom_vline(xintercept=6,color="black", linetype="dashed")+geom_vline(xintercept=5,color="black", linetype="dashed")+geom_vline(xintercept=4,color="black", linetype="dashed")+
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=12))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 12, colour = "black"))+theme(legend.position="none")#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("soilpH.pdf",width=3, height=2)
p1
dev.off()
```

##soil pH 
```{R plot}
def1<-read.csv("def1.csv")
def2<-read.csv("def2.csv")
def3<-read.csv("def3.csv")
def4<-read.csv("def4.csv")
def5<-read.csv("def5.csv")

test<-rbind(def1, def2, def3, def4, def5)


# fix number of decimal
scaleFUN <- function(x) sprintf("%.1f", x)

p1<-ggplot(test, aes(x=mu, y=pH, color=level))+geom_point()+ 
  geom_smooth(method=loess,aes(fill=NA))+scale_color_manual(values=c("#fee0b6","#fdb863","#e08214","#b35806","#7f3b08"))+geom_hline(yintercept=5.42,color="black", linetype="dashed")+
scale_fill_manual(values=c("#fee0b6","#fdb863","#e08214","#b35806","#7f3b08"))+ scale_x_continuous(name = 'Ionic strength (mmol/L)') + scale_y_continuous(name = 'pH',labels=scaleFUN)+ 
theme_linedraw()+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=14))+theme(strip.background = element_rect(fill="white"),strip.text.x = element_text(size = 14, colour = "black"))+theme(legend.position="none")#+theme(axis.text.x=element_text(angle =45, vjust = 0.5))
p1

pdf("muPH.pdf",width=4, height=2.5)
p1
dev.off()
```


```{r fph}
#====pH response function====
pH<-seq(2,12,0.01)
fpHref<-10^(-0.2235*pH^2+2.7727*pH -8.6)
f3<-fpHref/max(fpHref)

f2<-(pH-4)*(pH-10)/((pH-4)*(pH-10)-(pH-7)^2)

ph1<-seq(2,7,0.01)
fph1<-1.02/(1.02+10^6*exp(-2.5*ph1))
ph2<-seq(7.01,12,0.01)
fph2<-1.02/(1.02+10^6*exp(-2.5*(14-ph2)))

data1<-data.frame(pH=ph1)
data1$fpH1<-fph1

data2<-data.frame(pH=ph2)
data2$fpH1<-fph2

allf<-rbind(data1, data2)
allf$fpH2<-f2
allf$fpH3<-f3

fpHs<-melt(allf, id.var=c("pH"))

plot1<-ggplot(fpHs, aes(x = pH,y = value, color=variable)) +
  scale_x_continuous(name = 'pH', breaks=c(0,2,4,6,8,10,12,14)) +
  scale_y_continuous(name = 'Relative activity', limits=c(0,1)) + geom_line(aes(color=variable),size=1)+
  scale_color_manual(values =c("#fee0b6","#e08214","#7f3b08"))
plot2<-plot1+theme_linedraw()+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+theme(text = element_text(size=14))
plot2

pdf("fpH.pdf",width=5, height=2.8)
plot2
dev.off()
```